### ISSUE TITLE
UCI APIs - Get All Bots

### ISSUE THREAD

**Issue by aayushkedia95** [Samagra-Development/UCI#22]
- [x] Add Status attribute
- [x] Add Description attribute
- [x] Paginate 
- [x] Add Search by name API 
- [x] Add Start Date/End Date Attribute (in create a Bot API as well)
- [x] Add Enable/Disable API - Start, stop, pause.
- [x] Add User Segment Meta - Get Segment Name, Count with Ids

"users": [
	{ 
	"id": "0ed82f44-e857-443c-9010-90d3ab1b6793", 
	"name": "Segment", 
	"count": 14000
	}
]

**Comment by ChakshuGautam** [comment]
Pening Task List - Search

- [ ] Adding [fuzzymatch extension]( https://www.postgresql.org/docs/12/fuzzystrmatch.html).
- [ ] Updating API to implement fuzzy search in DB
